apiVersion: v1
kind: Service
metadata:
  name: {{ include "swe-platform.operatorMetricsFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swe-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  selector:
    app.kubernetes.io/name: {{ include "swe-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: operator
  ports:
    - name: metrics
      port: {{ int .Values.operator.metrics.port }}
      targetPort: metrics
