//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCredentialProfile) DeepCopyInto(out *AgentCredentialProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCredentialProfile.
func (in *AgentCredentialProfile) DeepCopy() *AgentCredentialProfile {
	if in == nil {
		return nil
	}
	out := new(AgentCredentialProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentCredentialProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCredentialProfileList) DeepCopyInto(out *AgentCredentialProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentCredentialProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCredentialProfileList.
func (in *AgentCredentialProfileList) DeepCopy() *AgentCredentialProfileList {
	if in == nil {
		return nil
	}
	out := new(AgentCredentialProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentCredentialProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCredentialProfileSpec) DeepCopyInto(out *AgentCredentialProfileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCredentialProfileSpec.
func (in *AgentCredentialProfileSpec) DeepCopy() *AgentCredentialProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AgentCredentialProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Environment) DeepCopyInto(out *Environment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Environment.
func (in *Environment) DeepCopy() *Environment {
	if in == nil {
		return nil
	}
	out := new(Environment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Environment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentActivityReceipt) DeepCopyInto(out *EnvironmentActivityReceipt) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentActivityReceipt.
func (in *EnvironmentActivityReceipt) DeepCopy() *EnvironmentActivityReceipt {
	if in == nil {
		return nil
	}
	out := new(EnvironmentActivityReceipt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentActivityRequest) DeepCopyInto(out *EnvironmentActivityRequest) {
	*out = *in
	out.EnvironmentLifecycleRequest = in.EnvironmentLifecycleRequest
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentActivityRequest.
func (in *EnvironmentActivityRequest) DeepCopy() *EnvironmentActivityRequest {
	if in == nil {
		return nil
	}
	out := new(EnvironmentActivityRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentEndpoints) DeepCopyInto(out *EnvironmentEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentEndpoints.
func (in *EnvironmentEndpoints) DeepCopy() *EnvironmentEndpoints {
	if in == nil {
		return nil
	}
	out := new(EnvironmentEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentHoldPolicy) DeepCopyInto(out *EnvironmentHoldPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentHoldPolicy.
func (in *EnvironmentHoldPolicy) DeepCopy() *EnvironmentHoldPolicy {
	if in == nil {
		return nil
	}
	out := new(EnvironmentHoldPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentLifecycleRequest) DeepCopyInto(out *EnvironmentLifecycleRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentLifecycleRequest.
func (in *EnvironmentLifecycleRequest) DeepCopy() *EnvironmentLifecycleRequest {
	if in == nil {
		return nil
	}
	out := new(EnvironmentLifecycleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentLifecycleSpec) DeepCopyInto(out *EnvironmentLifecycleSpec) {
	*out = *in
	if in.Hold != nil {
		in, out := &in.Hold, &out.Hold
		*out = new(EnvironmentHoldPolicy)
		**out = **in
	}
	if in.Wake != nil {
		in, out := &in.Wake, &out.Wake
		*out = new(EnvironmentWakeRequest)
		**out = **in
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(EnvironmentSuspendRequest)
		**out = **in
	}
	if in.Activity != nil {
		in, out := &in.Activity, &out.Activity
		*out = make([]EnvironmentActivityRequest, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentLifecycleSpec.
func (in *EnvironmentLifecycleSpec) DeepCopy() *EnvironmentLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentLifecycleStatus) DeepCopyInto(out *EnvironmentLifecycleStatus) {
	*out = *in
	if in.ActivityReceipts != nil {
		in, out := &in.ActivityReceipts, &out.ActivityReceipts
		*out = make([]EnvironmentActivityReceipt, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentLifecycleStatus.
func (in *EnvironmentLifecycleStatus) DeepCopy() *EnvironmentLifecycleStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentLifecycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentList) DeepCopyInto(out *EnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Environment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentList.
func (in *EnvironmentList) DeepCopy() *EnvironmentList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentPortalRoute) DeepCopyInto(out *EnvironmentPortalRoute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentPortalRoute.
func (in *EnvironmentPortalRoute) DeepCopy() *EnvironmentPortalRoute {
	if in == nil {
		return nil
	}
	out := new(EnvironmentPortalRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentProvisioningProject) DeepCopyInto(out *EnvironmentProvisioningProject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentProvisioningProject.
func (in *EnvironmentProvisioningProject) DeepCopy() *EnvironmentProvisioningProject {
	if in == nil {
		return nil
	}
	out := new(EnvironmentProvisioningProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentProvisioningSnapshot) DeepCopyInto(out *EnvironmentProvisioningSnapshot) {
	*out = *in
	out.Template = in.Template
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(map[string]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	out.DiskSize = in.DiskSize.DeepCopy()
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(EnvironmentProvisioningProject)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentProvisioningSnapshot.
func (in *EnvironmentProvisioningSnapshot) DeepCopy() *EnvironmentProvisioningSnapshot {
	if in == nil {
		return nil
	}
	out := new(EnvironmentProvisioningSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentProvisioningTemplate) DeepCopyInto(out *EnvironmentProvisioningTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentProvisioningTemplate.
func (in *EnvironmentProvisioningTemplate) DeepCopy() *EnvironmentProvisioningTemplate {
	if in == nil {
		return nil
	}
	out := new(EnvironmentProvisioningTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentRecoveryStatus) DeepCopyInto(out *EnvironmentRecoveryStatus) {
	*out = *in
	if in.NextAttemptAt != nil {
		in, out := &in.NextAttemptAt, &out.NextAttemptAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentRecoveryStatus.
func (in *EnvironmentRecoveryStatus) DeepCopy() *EnvironmentRecoveryStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentRecoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentServiceDeclaration) DeepCopyInto(out *EnvironmentServiceDeclaration) {
	*out = *in
	if in.Launch != nil {
		in, out := &in.Launch, &out.Launch
		*out = new(EnvironmentServiceLaunch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentServiceDeclaration.
func (in *EnvironmentServiceDeclaration) DeepCopy() *EnvironmentServiceDeclaration {
	if in == nil {
		return nil
	}
	out := new(EnvironmentServiceDeclaration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentServiceLaunch) DeepCopyInto(out *EnvironmentServiceLaunch) {
	*out = *in
	if in.Argv != nil {
		in, out := &in.Argv, &out.Argv
		*out = make([]EnvironmentServiceLaunchArgument, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentServiceLaunch.
func (in *EnvironmentServiceLaunch) DeepCopy() *EnvironmentServiceLaunch {
	if in == nil {
		return nil
	}
	out := new(EnvironmentServiceLaunch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentServiceObservation) DeepCopyInto(out *EnvironmentServiceObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentServiceObservation.
func (in *EnvironmentServiceObservation) DeepCopy() *EnvironmentServiceObservation {
	if in == nil {
		return nil
	}
	out := new(EnvironmentServiceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentServiceObservations) DeepCopyInto(out *EnvironmentServiceObservations) {
	*out = *in
	if in.ExecutionGeneration != nil {
		in, out := &in.ExecutionGeneration, &out.ExecutionGeneration
		*out = new(int64)
		**out = **in
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]EnvironmentServiceObservation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentServiceObservations.
func (in *EnvironmentServiceObservations) DeepCopy() *EnvironmentServiceObservations {
	if in == nil {
		return nil
	}
	out := new(EnvironmentServiceObservations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentSpec) DeepCopyInto(out *EnvironmentSpec) {
	*out = *in
	in.Lifecycle.DeepCopyInto(&out.Lifecycle)
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]EnvironmentServiceDeclaration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentSpec.
func (in *EnvironmentSpec) DeepCopy() *EnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentStatus) DeepCopyInto(out *EnvironmentStatus) {
	*out = *in
	if in.Provisioning != nil {
		in, out := &in.Provisioning, &out.Provisioning
		*out = new(EnvironmentProvisioningSnapshot)
		(*in).DeepCopyInto(*out)
	}
	in.Lifecycle.DeepCopyInto(&out.Lifecycle)
	if in.ClaimedBy != nil {
		in, out := &in.ClaimedBy, &out.ClaimedBy
		*out = new(RunReference)
		**out = **in
	}
	out.Endpoints = in.Endpoints
	if in.ServiceObservations != nil {
		in, out := &in.ServiceObservations, &out.ServiceObservations
		*out = new(EnvironmentServiceObservations)
		(*in).DeepCopyInto(*out)
	}
	if in.PortalRoutes != nil {
		in, out := &in.PortalRoutes, &out.PortalRoutes
		*out = make([]EnvironmentPortalRoute, len(*in))
		copy(*out, *in)
	}
	if in.LastActiveAt != nil {
		in, out := &in.LastActiveAt, &out.LastActiveAt
		*out = (*in).DeepCopy()
	}
	in.Recovery.DeepCopyInto(&out.Recovery)
	if in.PodRecoveryNextAttemptAt != nil {
		in, out := &in.PodRecoveryNextAttemptAt, &out.PodRecoveryNextAttemptAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentStatus.
func (in *EnvironmentStatus) DeepCopy() *EnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentSuspendRequest) DeepCopyInto(out *EnvironmentSuspendRequest) {
	*out = *in
	out.EnvironmentLifecycleRequest = in.EnvironmentLifecycleRequest
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentSuspendRequest.
func (in *EnvironmentSuspendRequest) DeepCopy() *EnvironmentSuspendRequest {
	if in == nil {
		return nil
	}
	out := new(EnvironmentSuspendRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentTemplate) DeepCopyInto(out *EnvironmentTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentTemplate.
func (in *EnvironmentTemplate) DeepCopy() *EnvironmentTemplate {
	if in == nil {
		return nil
	}
	out := new(EnvironmentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentTemplateList) DeepCopyInto(out *EnvironmentTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvironmentTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentTemplateList.
func (in *EnvironmentTemplateList) DeepCopy() *EnvironmentTemplateList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentTemplateSpec) DeepCopyInto(out *EnvironmentTemplateSpec) {
	*out = *in
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.WarmPool != nil {
		in, out := &in.WarmPool, &out.WarmPool
		*out = new(WarmPoolSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentTemplateSpec.
func (in *EnvironmentTemplateSpec) DeepCopy() *EnvironmentTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentTemplateStatus) DeepCopyInto(out *EnvironmentTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentTemplateStatus.
func (in *EnvironmentTemplateStatus) DeepCopy() *EnvironmentTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentWakeRequest) DeepCopyInto(out *EnvironmentWakeRequest) {
	*out = *in
	out.EnvironmentLifecycleRequest = in.EnvironmentLifecycleRequest
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentWakeRequest.
func (in *EnvironmentWakeRequest) DeepCopy() *EnvironmentWakeRequest {
	if in == nil {
		return nil
	}
	out := new(EnvironmentWakeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Installation) DeepCopyInto(out *Installation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Installation.
func (in *Installation) DeepCopy() *Installation {
	if in == nil {
		return nil
	}
	out := new(Installation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Installation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationCSIDriverIdentity) DeepCopyInto(out *InstallationCSIDriverIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationCSIDriverIdentity.
func (in *InstallationCSIDriverIdentity) DeepCopy() *InstallationCSIDriverIdentity {
	if in == nil {
		return nil
	}
	out := new(InstallationCSIDriverIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationIsolationSpec) DeepCopyInto(out *InstallationIsolationSpec) {
	*out = *in
	if in.RuntimeClass != nil {
		in, out := &in.RuntimeClass, &out.RuntimeClass
		*out = new(InstallationRuntimeClassExpectation)
		**out = **in
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(InstallationStorageClassExpectation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationIsolationSpec.
func (in *InstallationIsolationSpec) DeepCopy() *InstallationIsolationSpec {
	if in == nil {
		return nil
	}
	out := new(InstallationIsolationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationList) DeepCopyInto(out *InstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Installation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationList.
func (in *InstallationList) DeepCopy() *InstallationList {
	if in == nil {
		return nil
	}
	out := new(InstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationPolicyConfigMapIdentity) DeepCopyInto(out *InstallationPolicyConfigMapIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationPolicyConfigMapIdentity.
func (in *InstallationPolicyConfigMapIdentity) DeepCopy() *InstallationPolicyConfigMapIdentity {
	if in == nil {
		return nil
	}
	out := new(InstallationPolicyConfigMapIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationRuntimeClassExpectation) DeepCopyInto(out *InstallationRuntimeClassExpectation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationRuntimeClassExpectation.
func (in *InstallationRuntimeClassExpectation) DeepCopy() *InstallationRuntimeClassExpectation {
	if in == nil {
		return nil
	}
	out := new(InstallationRuntimeClassExpectation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationRuntimeClassIdentity) DeepCopyInto(out *InstallationRuntimeClassIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationRuntimeClassIdentity.
func (in *InstallationRuntimeClassIdentity) DeepCopy() *InstallationRuntimeClassIdentity {
	if in == nil {
		return nil
	}
	out := new(InstallationRuntimeClassIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationSpec) DeepCopyInto(out *InstallationSpec) {
	*out = *in
	if in.Isolation != nil {
		in, out := &in.Isolation, &out.Isolation
		*out = new(InstallationIsolationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationSpec.
func (in *InstallationSpec) DeepCopy() *InstallationSpec {
	if in == nil {
		return nil
	}
	out := new(InstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationStatus) DeepCopyInto(out *InstallationStatus) {
	*out = *in
	if in.ObservedIsolation != nil {
		in, out := &in.ObservedIsolation, &out.ObservedIsolation
		*out = new(InstallationIsolationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyConfigMap != nil {
		in, out := &in.PolicyConfigMap, &out.PolicyConfigMap
		*out = new(InstallationPolicyConfigMapIdentity)
		**out = **in
	}
	if in.RuntimeClass != nil {
		in, out := &in.RuntimeClass, &out.RuntimeClass
		*out = new(InstallationRuntimeClassIdentity)
		**out = **in
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(InstallationStorageClassIdentity)
		**out = **in
	}
	if in.CSIDriver != nil {
		in, out := &in.CSIDriver, &out.CSIDriver
		*out = new(InstallationCSIDriverIdentity)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationStatus.
func (in *InstallationStatus) DeepCopy() *InstallationStatus {
	if in == nil {
		return nil
	}
	out := new(InstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationStorageClassExpectation) DeepCopyInto(out *InstallationStorageClassExpectation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationStorageClassExpectation.
func (in *InstallationStorageClassExpectation) DeepCopy() *InstallationStorageClassExpectation {
	if in == nil {
		return nil
	}
	out := new(InstallationStorageClassExpectation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationStorageClassIdentity) DeepCopyInto(out *InstallationStorageClassIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationStorageClassIdentity.
func (in *InstallationStorageClassIdentity) DeepCopy() *InstallationStorageClassIdentity {
	if in == nil {
		return nil
	}
	out := new(InstallationStorageClassIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EgressAllowlist != nil {
		in, out := &in.EgressAllowlist, &out.EgressAllowlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Run) DeepCopyInto(out *Run) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Run.
func (in *Run) DeepCopy() *Run {
	if in == nil {
		return nil
	}
	out := new(Run)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Run) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunCredentialProfileReference) DeepCopyInto(out *RunCredentialProfileReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunCredentialProfileReference.
func (in *RunCredentialProfileReference) DeepCopy() *RunCredentialProfileReference {
	if in == nil {
		return nil
	}
	out := new(RunCredentialProfileReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunEnvironmentReference) DeepCopyInto(out *RunEnvironmentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunEnvironmentReference.
func (in *RunEnvironmentReference) DeepCopy() *RunEnvironmentReference {
	if in == nil {
		return nil
	}
	out := new(RunEnvironmentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunList) DeepCopyInto(out *RunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Run, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunList.
func (in *RunList) DeepCopy() *RunList {
	if in == nil {
		return nil
	}
	out := new(RunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunReference) DeepCopyInto(out *RunReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunReference.
func (in *RunReference) DeepCopy() *RunReference {
	if in == nil {
		return nil
	}
	out := new(RunReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunSpec) DeepCopyInto(out *RunSpec) {
	*out = *in
	if in.Notify != nil {
		in, out := &in.Notify, &out.Notify
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunSpec.
func (in *RunSpec) DeepCopy() *RunSpec {
	if in == nil {
		return nil
	}
	out := new(RunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunStatus) DeepCopyInto(out *RunStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.EnvironmentRef != nil {
		in, out := &in.EnvironmentRef, &out.EnvironmentRef
		*out = new(RunEnvironmentReference)
		**out = **in
	}
	if in.CredentialProfileRef != nil {
		in, out := &in.CredentialProfileRef, &out.CredentialProfileRef
		*out = new(RunCredentialProfileReference)
		**out = **in
	}
	if in.AcceptedEnvironmentEpoch != nil {
		in, out := &in.AcceptedEnvironmentEpoch, &out.AcceptedEnvironmentEpoch
		*out = new(int64)
		**out = **in
	}
	if in.AcceptedEnvironmentExecutionGeneration != nil {
		in, out := &in.AcceptedEnvironmentExecutionGeneration, &out.AcceptedEnvironmentExecutionGeneration
		*out = new(int64)
		**out = **in
	}
	out.Usage = in.Usage
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunStatus.
func (in *RunStatus) DeepCopy() *RunStatus {
	if in == nil {
		return nil
	}
	out := new(RunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunUsage) DeepCopyInto(out *RunUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunUsage.
func (in *RunUsage) DeepCopy() *RunUsage {
	if in == nil {
		return nil
	}
	out := new(RunUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmPoolSpec) DeepCopyInto(out *WarmPoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmPoolSpec.
func (in *WarmPoolSpec) DeepCopy() *WarmPoolSpec {
	if in == nil {
		return nil
	}
	out := new(WarmPoolSpec)
	in.DeepCopyInto(out)
	return out
}
