image:
  repository: ghcr.io/chris-cullins/swe-platform/operator
  tag: dev
  pullPolicy: IfNotPresent

controlPlane:
  image:
    tag: dev

leaderElection: false

environmentTemplates:
  - name: small
    spec:
      image: ghcr.io/chris-cullins/swe-platform/env-base:dev
      size: small
      idleTimeout: 15m
      diskSize: 5Gi
